version: "3.8"

services:
  gerrit:
    image: gerritcodereview/gerrit
    restart: unless-stopped
    ports:
      - "29418:29418"
      - "8080:8080"
    environment:
      CANONICAL_WEB_URL: ${GERRIT_CANONICAL_WEB_URL:-http://localhost:8080}
    volumes:
      - git-volume:/var/gerrit/git
      - index-volume:/var/gerrit/index
      - cache-volume:/var/gerrit/cache

  jenkins:
    build:
      context: jenkins
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    restart: unless-stopped
    ports:
      - 8081:8080
      - 50000:50000
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.admin=admin --argumentsRealm.roles.user=${JENKINS_USERNAME:-admin} --argumentsRealm.passwd.admin=${JENKINS_PASSWORD:-admin}
    volumes:
      - jenkins-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  git-volume:
  index-volume:
  cache-volume:
  jenkins-volume:
