version: "3.8"

services:
  gerrit:
    image: gerritcodereview/gerrit:3.2.3
    restart: unless-stopped
    ports:
      - "29418:29418"
      - "8080:8080"
    environment:
      CANONICAL_WEB_URL: "${GERRIT_CANONICAL_WEB_URL:-http://localhost:8080}"
    volumes:
      - "git-volume:/var/gerrit/git"
      - "index-volume:/var/gerrit/index"
      - "cache-volume:/var/gerrit/cache"
      - "etc-volume:/var/gerrit/etc"
      - "db-volume:/var/gerrit/db"

  jenkins:
    build:
      context: jenkins
      args:
        HOST_GID: "${HOST_GID}"
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "${CASC_JENKINS_CONFIG:-/usr/share/jenkins/ref/JCasC}"
      JENKINS_OPTS: "--argumentsRealm.roles.admin=admin --argumentsRealm.roles.user=${JENKINS_USERNAME:-jenkins} --argumentsRealm.passwd.admin=${JENKINS_PASSWORD:-jenkins}"
      JENKINS_USERNAME: "${JENKINS_USERNAME:-jenkins}"
      JENKINS_PASSWORD: "${JENKINS_PASSWORD:-jenkins}"
      JENKINS_URL: "${JENKINS_URL:-http://localhost:8081}"
      JENKINS_JOB_DSL_SEED_NAME: "${JENKINS_JOB_DSL_SEED_NAME:-JCasC-Job-DSL-Seed}"
      GERRIT_PROJECT_NAME: "${GERRIT_PROJECT_NAME:-gerrit-jenkins-test}"
    volumes:
      - "jenkins-volume:/var/jenkins_home"
      - "./jenkins/JCasC:${CASC_JENKINS_CONFIG:-/usr/share/jenkins/ref/JCasC}"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  git-volume:
  index-volume:
  cache-volume:
  jenkins-volume:
  etc-volume:
  db-volume:
