pipeline {
    agent { docker { image 'python:3.5.1' } }
    stages {
        stage('build') {
            steps {
                sh 'python --version'
            }
        }
    }
     post {
        success { gerritReview labels: ['Code-Review': 1] }
        unstable { gerritReview labels: ['Code-Review': 0] }
        failure { gerritReview labels: ['Code-Review': -1] }
    }
}