jobs:
  - script: >
      job("${JENKINS_JOB_DSL_SEED_NAME}") {
        scm {
          git {
            remote {
              url("http://gerrit:8080/${GERRIT_PROJECT_NAME}")
              credentials('gerrit-jenkins-user')
            }
            branches('master')
          }
        }
        steps {
          jobDsl {
            targets('jobs/**/*.groovy')
            ignoreMissingFiles(true)
          }
        }
      }
