jobs:
  - script: >
      job('JCasC-Job-DSL-Seed') {
        scm {
          git {
            remote {
              url "http://gerrit:8080/${GERRIT_PROJECT_NAME}"
            }
          }
        }
        steps {
          jobDsl {
            targets 'jobs/**/*.groovy'
          }
        }
      }
